# before running please install pytorch dependencies:
# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
# conda env update -f requirements.yaml

name: robo-proj
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pip
  - python
  - tqdm
  - scipy
  - opencv
  - scikit-image
  - glfw
  - ipykernel
  - ipywidgets
  - pip:
      - mujoco
      - scikit-opt
      - mealpy
platforms:
  - linux-64